--- 
name: rhodes-system-api-samples
capabilities: 
- gps
- pim
- camera
- vibrate
- phone
- bluetooth
- calendar

bbver: 5.0
sdk: /Users/evgeny/Projects/rhodes
applog: rholog.txt
version: 1.0.7
vendor: rhomobile
iphone: 
  emulator: 4.0.2
  sdk: iphonesimulator4.0
  codesignidentity: ""
  entitlements: ""
  configuration: Debug
  extensions: ["barcode", "rainbow"]
  
wm:
  extensions: ["barcode"] #, "rainbow"]
bb:
  extensions: ["barcode"]
android:
  extensions: ["barcode", "rainbow"]
  capabilities:
  - network_state
  - sdcard
  mapping: yes

extensions: ["json", "rhoxml"]
