--- 
name: rhodes-system-api-samples
capabilities: 
- gps
- pim
- camera
- vibrate
- phone
- bluetooth
- calendar

bbver: 5.0
#sdk: c:/Projects/rhodes
#sdk: C:\Ruby192\lib\ruby\gems\1.9.1\gems\rhodes-3.2.0.beta.4
#sdkversion: 3.0.1

applog: rholog.txt
version: 1.0.7
vendor: rhomobile
iphone: 
  emulator: 4.0.2
  sdk: iphonesimulator4.0
  codesignidentity: ""
  entitlements: ""
  configuration: Debug
  extensions: ["barcode", "rainbow", "digest", "digest-md5", "digest-sha1"]
  
wm:
  extensions: ["rainbow", "digest", "digest-md5", "digest-sha1"] #"barcode",
bb:
  extensions: ["barcode"]
android:
  extensions: ["barcode", "rainbow", "nfc", "digest", "digest-md5", "digest-sha1"]
  capabilities:
  - network_state
  - sdcard
  - calendar
  mapping: yes
  version: 2.1

wp:
  productid: 'fd55c4d0-51fa-012e-7844-3caec51bd50e'

extensions: ["json", "rhoxml", "rhodes_translator"]

symbian: 
  uid: 3780829571

