--- 
name: rhodes-system-api-samples
capabilities: 
- gps
- pim
- camera
- vibrate
- phone
bbver: 4.6.1
android: 
  capabilities: 
  - network_state
  mapping: true
sdk: /Users/evgeny/Projects/rhodes
applog: rholog.txt
version: 1.0.7
vendor: rhomobile
iphone: 
  emulator: 4.0.2
  sdk: iphonesimulator4.0
  codesignidentity: ""
  entitlements: ""
  configuration: Debug
  extensions: ["barcode", "rainbow"]
  
wm:
  extensions: ["barcode"]
bb:
  extensions: ["barcode"]
android:
  extensions: ["barcode"]

extensions: ["rhodes_translator", "json", "rhoxml"]