--- 
name: rhodes-system-api-samples
capabilities: 
- gps
- pim
- camera
- vibrate
- phone
- bluetooth
- calendar

bbver: 7.0
sdk: c:/Projects/rhodes
#sdk: "E:/_proj/rhomobile/rhodes"
#sdkversion: 3.0.1

applog: rholog.txt
version: 1.0.7
vendor: rhomobile
iphone: 
  emulator: 4.0.2
  sdk: iphonesimulator4.0
  codesignidentity: ""
  entitlements: ""
  configuration: Debug
  extensions: ["barcode", "rainbow"]
  
wm:
  extensions: ["rainbow"] #"barcode",
bb:
  extensions: ["barcode"]
android:
  extensions: ["barcode", "rainbow", "nfc"]
  capabilities:
  - network_state
  - sdcard
  - calendar
  mapping: yes
  version: 2.1

wp:
  productid: 'fd55c4d0-51fa-012e-7844-3caec51bd50e'

extensions: ["json", "rhoxml"]
