--- 
name: rhodes-system-api-samples
bbver: 4.6.1
sdk: ~/rhodes/
applog: rholog.txt
version: 1.0.7
vendor: rhomobile

#extensions: ["rexml", "set"]

capabilities:
  - gps
  - pim
  - camera
  - vibrate
  - phone
 
iphone: 
  sdk: iphonesimulator3.0
  entitlements: ""
  codesignidentity: ""
  configuration: Debug

android:
  mapping: yes
  capabilities:
    - network_state

