--- 
name: rhodes-system-api-samples
capabilities: 
- gps
- pim
- camera
- vibrate
- phone
- bluetooth
- calendar
#- motorola

bbver: 5.0
#sdk: c:/Projects/rhodes

applog: rholog.txt
version: 1.0.7
vendor: rhomobile
iphone: 
  emulator: 5.0
  sdk: iphonesimulator5.0
  codesignidentity: ""
  entitlements: ""
  entitlements_file: "./production/Entitlements.plist"
  configuration: Debug
  extensions: ["barcode", "rainbow", "digest", "digest-md5", "digest-sha1"]
  production:
    app_plist_title: "SAS"
    app_plist_subtitle: "SAS"
    app_plist_icon_url: "www.sas.com/icon.png"
    app_plist_ipa_url: "www.sas.com/sas.ipa"
    ipa_itunesartwork_image: "./production/image.jpg"  
  
wm:
  extensions: ["digest", "digest-md5", "digest-sha1"] #, "barcode-moto", "webkit-browser"]
  #"rainbow"
  #sdk: "MC3000c50b (ARMV4I)"

bb:
  extensions: ["barcode"]

android:
  extensions: ["barcode", "rainbow", "nfc", "digest", "digest-md5", "digest-sha1"]
  capabilities:
  - network_state
  - sdcard
  - calendar
  mapping: yes
  version: 2.1

wp:
  productid: 'fd55c4d0-51fa-012e-7844-3caec51bd50e'

extensions: ["json", "rhoxml", "rhodes_translator"]

symbian: 
  uid: 3780829571

